### ISSUE TITLE
Unit testing?

### ISSUE THREAD

**Issue by karllhughes** [ryanxada/aero#1]
Love the idea here, Ryan. How about testing? I know your goal is to keep the framework lightweight, but it seems like some framework for testing should be included? Maybe just requiring PHPUnit in the compose require-dev line and a folder for tests?

Just a thought!

**Comment by ryanxada** [comment]
My initial thought was not to tie the core to a particular testing framework but since PHP Unit is so ubiquitous I think ultimately it makes sense.

**Comment by karllhughes** [comment]
Cool, thanks, @ryanxada . I'd love to hear more about your goals for this project. I know there are a lot of PHP micro-frameworks out there. Where do you see yours fitting into the mix? I've been thinking of getting involved in a couple new open source projects, so I'm just curious.

Feel free to respond via email if that's easier: khughes.me@gmail.com

Thanks!

**Comment by ryanxada** [comment]
@karllhughes thanks for asking and your contribution. I created aero for developers (like me) who prefer to do almost everything from scratch, but still want to take advantage of the very base components from popular frameworks and avoid reinventing the wheel. The goal was really to see just how small a footprint I could leave while still building a solid and extensible core.

I've worked with WordPress and more recently Laravel/Lumen as a backend for years and they covered about 80% of what I needed. I found them all to be overkill on smaller-scale sites but the methodologies behind Laravel especially are fantastic. [Lumen](https://github.com/laravel/lumen) is about as solid as they come as far as micro-frameworks go, but again it was just a little too polished for the sites I found myself building a lot of.

The future of the project rests with the good folks like yourself who see the value in having a purposefully light framework to plug into. I think it would be a really exciting challenge to see just how light it can stay while providing developers the ability to add other components (db,auth,front-end packages, etc...) as their project needs change. You can totally do that now through composer, but I think there's definitely a balance between feature additions and bloat and I want to stay very cognizant of that.

I'm not a big fan of the "plugin" ecosystem but component-based development is where it's at for me. I think it's prudent to encourage the people who build websites/software for other people to get into the guts of the framework and really understand what's going on under the hood. This framework is for dev's who want to be fairly involved in their builds but also don't want to waste time configuring standalone templating and routing.

If you have any ideas, I'd really like to hear them. In the meantime, I just hope you and anyone else who wanders by finds it useful. I am using it in production right now and I really dig it. It was featured on @thechangelog 's weekly email recently so here's hoping the word gets out. If you're thinking about spending some time contributing to open-source they are an incredible resource.

**Comment by karllhughes** [comment]
@ryanxada I like it, and I do have some thoughts! 

This conversation is worthy of it's own issue, so I'm going to open a new one up with your comment at the top and leave a reply there. This will be helpful in case more contributors come in in the future.
