### ISSUE TITLE
Improving documentation

### ISSUE THREAD

**Issue by karllhughes** [ryanxada/aero#10]
In the interest of making our project as beginner friendly as possible, let's make sure we document things well. Some things that I think would be great to add:

- Details on what aero does and does not provide to developers (eg: we do include routing, views. Don't include any opinion on data storage or ORM)
- Basic introduction to unit tests with PHPUnit
- Examples for using aero in projects: 
  - Creating a landing page with aero
  - Setting up a blog with aero
  - Setting up a purchase form with aero

**Comment by ryanxada** [comment]
I've gotten a few questions in the last day or two about where I see this project headed and if I would consider broadening the scope. Before tackling the documentation updates I want to give it some thought. I'll post to this thread in the next few days and we can divide and conquer on the docs.

**Comment by ryanxada** [comment]
@karllhughes hey if you're interested I'd like to open areo up to go in a broader direction. Whatever you think will improve the experience - please PR and it'll most likely get in. I'm spinning off the original codebase into a project with a different objective - leaving aero open for whatever. If you're inclined to keep contributing - please have at it :beers:
