### ISSUE TITLE
Why Aero?

### ISSUE THREAD

**Issue by karllhughes** [ryanxada/aero#3]
I asked @ryanxada what role he felt aero might play in the PHP ecosystem. His reply might spark further conversation so I've copied it here:

-----

I created aero for developers (like me) who prefer to do almost everything from scratch, but still want to take advantage of the very base components from popular frameworks and avoid reinventing the wheel. The goal was really to see just how small a footprint I could leave while still building a solid and extensible core.

I've worked with WordPress and more recently Laravel/Lumen as a backend for years and they covered about 80% of what I needed. I found them all to be overkill on smaller-scale sites but the methodologies behind Laravel especially are fantastic. Lumen is about as solid as they come as far as micro-frameworks go, but again it was just a little too polished for the sites I found myself building a lot of.

The future of the project rests with the good folks like yourself who see the value in having a purposefully light framework to plug into. I think it would be a really exciting challenge to see just how light it can stay while providing developers the ability to add other components (db,auth,front-end packages, etc...) as their project needs change. You can totally do that now through composer, but I think there's definitely a balance between feature additions and bloat and I want to stay very cognizant of that.

I'm not a big fan of the "plugin" ecosystem but component-based development is where it's at for me. I think it's prudent to encourage the people who build websites/software for other people to get into the guts of the framework and really understand what's going on under the hood. This framework is for dev's who want to be fairly involved in their builds but also don't want to waste time configuring standalone templating and routing.

If you have any ideas, I'd really like to hear them. In the meantime, I just hope you and anyone else who wanders by finds it useful. I am using it in production right now and I really dig it. It was featured on @thechangelog 's weekly email recently so here's hoping the word gets out. If you're thinking about spending some time contributing to open-source they are an incredible resource.

[Original comment](https://github.com/ryanxada/aero/issues/1#issuecomment-143905597)

**Comment by karllhughes** [comment]
I saw the project on the Changelog's weekly email actually. I've been casually looking for a new open source project or two and thought a framework might be interesting. 

I'm a big fan of Laravel/Lumen, but to be honest I've never cracked them open and figured out how the whole thing works. I know a little about the [IoC container](http://code.tutsplus.com/tutorials/digging-in-to-laravels-ioc-container--cms-22167) and I've used a few of the composer packages on their own, but I know very little about the routing or views process, so aero appealed to me. I think it would be really cool to just learn how a simple framework works from the inside out by helping create it, hence my interest in aero.

Totally agree that Wordpress is way too much overhead for many projects, and even Laravel is bulkier than most projects need. That said, Laravel and Lumen probably both have some ideas that would benefit this project as well.

So, I'll open up some further issues to discuss specifics, but overall, I like the idea here, and I'm looking forward to helping out as I have time.

**Comment by ryanxada** [comment]
That's great to hear because it is exactly what I was hoping people would get out of it. I wanted something approachable yet was able to handle some fairly heavy lifting out of the box. The feedback so far has been really encouraging so I'm excited to see where it goes and if people are willing to share anything cool that they've built with it.

**Comment by ryanxada** [comment]
I think it's important to share that the main goal of this project is to offer developers an alternative to larger frameworks when building less-complex websites/apps. It *can* scale to thousands of pages if that works for your needs, but in the same way [Ghost](https://ghost.org/) isn't trying to be anything other than a blogging platform, aero isn't trying to be anything other than a super easy, unopinionated way to start a project using best practices in templating and routing. 

The learning curve is purposefully short. but the extensibility is potentially enormous depending on your needs, and that's where I'm hoping others find value. I think it definitely has room to grow, but simplicity and approachability are the guiding principles.
