### ISSUE TITLE
Allowing aero to be installed using Composer

### ISSUE THREAD

**Issue by karllhughes** [ryanxada/aero#4]
What do you think about releasing aero as its own Composer package? 

[Laravel](http://laravel.com/docs/5.1#installation) and [Flight](https://github.com/mikecao/flight#installation) both do this by releasing their apps as a composer package. I believe we just have to fill out the composer file a little more.

The only reason I see to hold off on this might be to wait until we're on a stricter semantic versioning and/or we move the repo to an organization account, which makes it easier to share with other contributors.

No need to rush on this, but it would make starting a project with aero faster/easier.

**Comment by ryanxada** [comment]
I think it's a great idea but for some of the reasons you mentioned above, I was hoping to mature the project a bit and gauge overall interest before taking it to the next level. All signs are pointing to a composer package as a great next step to shoot for though.

**Comment by ryanxada** [comment]
Going to take your suggestions and work on this tonight. Possible Composer package release later in the day.

**Comment by ryanxada** [comment]
Aero is now available to install via composer and uses semantic versioning. I am opting to keep this under my account for the time being but if more requests come in I would definitely reconsider moving it to its own organization.  @karllhughes great suggestions so far and looking forward to any other ideas. :beers:

**Comment by karllhughes** [comment]
:+1:
