### ISSUE TITLE
JSON responses

### ISSUE THREAD

**Issue by karllhughes** [ryanxada/aero#5]
So one common use case I might have for a microframework is to create a lightweight API that provides data in JSON rather than as an HTML view. I know the goal here is to be minimal with the framework, but do you have any idea how we might allow JSON instead of HTML views?

I'll look into this a little as well.

**Comment by ryanxada** [comment]
My first thought is that writing API's with aero is outside the scope of the projects original intent. There are many other tools out there that would be better suited for this kind of application. I know it's definitely missing the sugar that's worked into the more robust micro-frameworks out there, but I think that's an important part of what sets this framework apart. Great idea and definitely a valid real world scenario but for now the approachability of the set-up is my main concern.
