### ISSUE TITLE
Thoughts about name change?

### ISSUE THREAD

**Issue by karllhughes** [ryanxada/aero#6]
Just did some googling and this is the first result for aero php: https://code.google.com/p/aero-php/

Fortunately, the project is dead, but the author spun off this project from it: https://github.com/chromice/ae

Not sure if he's going to care that we're using his name, but it's easier to change the name of our project now than it will be in 6 months.

Just a thought. I think we can overtake the other entry in Google pretty quickly, but I wanted to make sure it was on our radar.

**Comment by ryanxada** [comment]
When I was first trying to come up with a name for the project, I thought of [Aerogel](https://en.wikipedia.org/wiki/Aerogel) - the ultra-light industrial material and thought this project shared enough of the same characteristics that it would be a good fit. I googled it at the time and came across the aero-php project you mentioned above, but as the author stated it's clearly dead so I didn't think he'd mind; plus this project is so vastly different. 

I agree with your point that a name change now would be easier than in the future, but I suppose I'd need some compelling evidence to change at this point. Of course I want to give it every chance I can to be discovered, but I would hope the rankings take care of themselves if enough people give it a go. I'll leave this issue open and we can revisit if it starts picking up steam.

**Comment by karllhughes** [comment]
Cool. No need to change the name. It'll be pretty easy to overtake a dead project in search results. :+1:
