### ISSUE TITLE
Running stats

### ISSUE THREAD

**Issue by ryanxada** [ryanxada/aero#8]
@karllhughes just thought I'd share some traffic stats in case you were interested.

09/25/15 - 09/30/15

Views: 1,025
Unique visitors: 187
Clones: 11
Unique Cloners: 7

Cheers!

**Comment by karllhughes** [comment]
Sweet! Thanks for considering all my PR's and questions. It's been a cool project to dig into with a bit of my free time.

**Comment by ryanxada** [comment]
It's been fun so far and I've learned a lot from your suggestions. :beers:
